export const reviewResponse = {
    "repo": "aditisingh98/mergewise-ai-review-platform",
    "prNumber": 2,
    "fileChanges": [
        {
            "filename": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "status": "added",
            "additions": 73,
            "deletions": 0,
            "changes": 73,
            "previousFilename": null,
            "patch": "@@ -0,0 +1,73 @@\n+import java.util.*;\n+\n+public class PaymentService {\n+\n+    public static void main(String[] args) {\n+        PaymentService service = new PaymentService();\n+        service.processPayment(null);\n+    }\n+\n+    public void processPayment(PaymentRequest request) {\n+\n+        // ❌ NullPointerException (request can be null)\n+        String customerId = request.getCustomerId();\n+\n+        System.out.println(\"Processing payment for: \" + customerId);\n+\n+        try {\n+            // ❌ NumberFormatException if amount is invalid\n+            int amount = Integer.parseInt(request.getAmount());\n+\n+            // ❌ Divide by zero possibility\n+            int result = 100 / request.getInstallments();\n+\n+            System.out.println(\"Calculated value: \" + result);\n+\n+            // ❌ NullPointerException if paymentMethods is null\n+            for (String method : request.getPaymentMethods()) {\n+                System.out.println(method.toUpperCase());\n+            }\n+\n+            // ❌ IndexOutOfBoundsException\n+            List<String> list = new ArrayList<>();\n+            System.out.println(list.get(0));\n+\n+        } catch (Exception e) {\n+            // ❌ Bad practice: generic exception + no proper logging\n+            System.out.println(\"Something went wrong\");\n+        }\n+\n+        // ❌ NullPointerException\n+        if (request.getStatus().equals(\"SUCCESS\")) {\n+            System.out.println(\"Payment success\");\n+        }\n+    }\n+}\n+\n+class PaymentRequest {\n+    private String customerId;\n+    private String amount;\n+    private Integer installments;\n+    private List<String> paymentMethods;\n+    private String status;\n+\n+    public String getCustomerId() {\n+        return customerId;\n+    }\n+\n+    public String getAmount() {\n+        return amount;\n+    }\n+\n+    public Integer getInstallments() {\n+        return installments;\n+    }\n+\n+    public List<String> getPaymentMethods() {\n+        return paymentMethods;\n+    }\n+\n+    public String getStatus() {\n+        return status;\n+    }\n+}\n\\ No newline at end of file",
            "addedLines": [
                "import java.util.*;",
                "public class PaymentService {",
                "    public static void main(String[] args) {",
                "        PaymentService service = new PaymentService();",
                "        service.processPayment(null);",
                "    }",
                "    public void processPayment(PaymentRequest request) {",
                "        // ❌ NullPointerException (request can be null)",
                "        String customerId = request.getCustomerId();",
                "        System.out.println(\"Processing payment for: \" + customerId);",
                "        try {",
                "            // ❌ NumberFormatException if amount is invalid",
                "            int amount = Integer.parseInt(request.getAmount());",
                "            // ❌ Divide by zero possibility",
                "            int result = 100 / request.getInstallments();",
                "            System.out.println(\"Calculated value: \" + result);",
                "            // ❌ NullPointerException if paymentMethods is null",
                "            for (String method : request.getPaymentMethods()) {",
                "                System.out.println(method.toUpperCase());",
                "            }",
                "            // ❌ IndexOutOfBoundsException",
                "            List<String> list = new ArrayList<>();",
                "            System.out.println(list.get(0));",
                "        } catch (Exception e) {",
                "            // ❌ Bad practice: generic exception + no proper logging",
                "            System.out.println(\"Something went wrong\");",
                "        }",
                "        // ❌ NullPointerException",
                "        if (request.getStatus().equals(\"SUCCESS\")) {",
                "            System.out.println(\"Payment success\");",
                "        }",
                "    }",
                "}",
                "class PaymentRequest {",
                "    private String customerId;",
                "    private String amount;",
                "    private Integer installments;",
                "    private List<String> paymentMethods;",
                "    private String status;",
                "    public String getCustomerId() {",
                "        return customerId;",
                "    }",
                "    public String getAmount() {",
                "        return amount;",
                "    }",
                "    public Integer getInstallments() {",
                "        return installments;",
                "    }",
                "    public List<String> getPaymentMethods() {",
                "        return paymentMethods;",
                "    }",
                "    public String getStatus() {",
                "        return status;",
                "    }",
                "}"
            ],
            "removedLines": [],
            "language": "java",
            "module": "java",
            "microservice": null,
            "backendCritical": true,
            "riskScore": 95
        }
    ],
    "reviewIssues": [
        {
            "id": "4b24c076-8a94-486c-b63d-6820f95c756b",
            "severity": "LOW",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Wildcard import hides which classes are used.",
            "description": "[low] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Wildcard import hides which classes are used.",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Replace the wildcard import with explicit imports for the classes used.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "81b3d256-6d69-4a24-805b-3d80ed30db35",
            "severity": "MEDIUM",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Dereferences `service` without a visible null check: service.processPayment(null);",
            "description": "[medium] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Dereferences `service` without a visible null check: service.processPayment(null);",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Add `service != null` check, use Optional, or annotate the value to make its nullability explicit.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "34094b90-2b1f-4dbf-bc21-1a8fe7364459",
            "severity": "MEDIUM",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Dereferences `request` without a visible null check: String customerId = request.getCustomerId();",
            "description": "[medium] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Dereferences `request` without a visible null check: String customerId = request.getCustomerId();",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Add `request != null` check, use Optional, or annotate the value to make its nullability explicit.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "7e2bff59-4a1a-485d-9983-6c92c8d9d9cb",
            "severity": "LOW",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Uses System.out/System.err instead of a logger.",
            "description": "[low] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Uses System.out/System.err instead of a logger.",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Use the SLF4J logger (e.g. log.info / log.error) instead of System.out.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "836fc4ee-6915-4008-ac92-29555c707ab2",
            "severity": "MEDIUM",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Dereferences `request` without a visible null check: int amount = Integer.parseInt(request.getAmount());",
            "description": "[medium] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Dereferences `request` without a visible null check: int amount = Integer.parseInt(request.getAmount());",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Add `request != null` check, use Optional, or annotate the value to make its nullability explicit.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "a2539d16-e324-4a0e-a226-038798834fc0",
            "severity": "MEDIUM",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Dereferences `request` without a visible null check: int result = 100 / request.getInstallments();",
            "description": "[medium] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Dereferences `request` without a visible null check: int result = 100 / request.getInstallments();",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Add `request != null` check, use Optional, or annotate the value to make its nullability explicit.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "ab4102c5-82cd-4f9d-86d4-598df40cf93c",
            "severity": "LOW",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Uses System.out/System.err instead of a logger.",
            "description": "[low] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Uses System.out/System.err instead of a logger.",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Use the SLF4J logger (e.g. log.info / log.error) instead of System.out.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "e8b383e2-cdae-4499-a0d4-0a3679dda963",
            "severity": "MEDIUM",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Dereferences `request` without a visible null check: for (String method : request.getPaymentMethods()) {",
            "description": "[medium] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Dereferences `request` without a visible null check: for (String method : request.getPaymentMethods()) {",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Add `request != null` check, use Optional, or annotate the value to make its nullability explicit.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "002b324a-c72e-4769-afe0-9d637032b2aa",
            "severity": "LOW",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Uses System.out/System.err instead of a logger.",
            "description": "[low] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Uses System.out/System.err instead of a logger.",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Use the SLF4J logger (e.g. log.info / log.error) instead of System.out.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "701d0dc7-5886-4763-92b4-4c74102df521",
            "severity": "LOW",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Uses System.out/System.err instead of a logger.",
            "description": "[low] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Uses System.out/System.err instead of a logger.",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Use the SLF4J logger (e.g. log.info / log.error) instead of System.out.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "e6644149-e0a9-4227-81b0-60a811559fb8",
            "severity": "LOW",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Uses System.out/System.err instead of a logger.",
            "description": "[low] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Uses System.out/System.err instead of a logger.",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Use the SLF4J logger (e.g. log.info / log.error) instead of System.out.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "edc655e6-960b-47c1-a5c1-880a4cf28bf7",
            "severity": "MEDIUM",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Dereferences `request` without a visible null check: if (request.getStatus().equals(\"SUCCESS\")) {",
            "description": "[medium] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Dereferences `request` without a visible null check: if (request.getStatus().equals(\"SUCCESS\")) {",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Add `request != null` check, use Optional, or annotate the value to make its nullability explicit.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "251c2401-9340-43ec-9b4e-03266ff37e48",
            "severity": "LOW",
            "category": "STATIC_ANALYSIS",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Uses System.out/System.err instead of a logger.",
            "description": "[low] src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Uses System.out/System.err instead of a logger.",
            "productionImpact": "Static analysis signal; validate in context before merge.",
            "fixRecommendation": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java - Use the SLF4J logger (e.g. log.info / log.error) instead of System.out.",
            "fixedCodeExample": "",
            "confidenceScore": 70
        },
        {
            "id": "fff4a002-9e0a-4387-8644-5c197670de3d",
            "severity": "MEDIUM",
            "category": "AI_REVIEW",
            "file": "AI provider",
            "line": 0,
            "title": "AI API request failed with 400 BAD_REQUEST",
            "description": "ISSUE: [medium] AI provider - AI API request failed with 400 BAD_REQUEST",
            "productionImpact": "See AI analysis in description.",
            "fixRecommendation": "AI provider - Check OPENAI_BASE_URL, OPENAI_API_KEY, OPENAI_MODEL, account quota, and request size before retrying.",
            "fixedCodeExample": "",
            "confidenceScore": 75
        },
        {
            "id": "faf229f8-3cef-4b97-9f71-5d557e7f85c5",
            "severity": "MEDIUM",
            "category": "CODE_QUALITY",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "Large Code Change Detected",
            "description": "Large patch size may reduce maintainability and review quality",
            "productionImpact": "Large unreviewed code changes increase production regression risk",
            "fixRecommendation": "Split PR into smaller logical commits",
            "fixedCodeExample": "Break changes into smaller feature-based pull requests",
            "confidenceScore": 82
        },
        {
            "id": "8253bf3b-a38d-4cda-9415-c153ee554b40",
            "severity": "LOW",
            "category": "LOGGING",
            "file": "src/main/java/com/mergewise/mergewise_backend/controller/PaymentService.java",
            "line": 0,
            "title": "System.out.println Detected",
            "description": "System.out.println should not be used in production applications",
            "productionImpact": "Logs will not integrate properly with observability systems",
            "fixRecommendation": "Use Slf4j logger instead",
            "fixedCodeExample": "log.info(\"message\");",
            "confidenceScore": 95
        }
    ],
    "metadata": {
        "aiReviewEnabled": true,
        "backendCriticalFiles": 1
    },
    "complete": true,
    "overallScore": 95,
    "riskLevel": "CRITICAL",
    "finalDecision": "CHANGES_REQUIRED"
}